export const FB_LOGIN_SUCCESS = 'FB_LOGIN_SUCCESS';
export const FB_LOGIN_REQUEST = 'FB_LOGIN_REQUEST';
export const FB_LOGIN_FAILURE = 'FB_LOGIN_FAILURE';
export const FB_TOKEN_IDENTIFIER = 'FB_TOKEN_IDENTIFIER';
